// <auto-generated />
namespace WebAPI_Finder_Test.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class DeletePhotos : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(DeletePhotos));
        
        string IMigrationMetadata.Id
        {
            get { return "201802221945213_Delete Photos"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
